spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon-api
    username: gigaamiridze
    password: gigaamiridze2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
